name: Update README

on:
  push:
    branches:
      - "**"
    paths:
      - action.yaml
      - .github/workflows/update-readme.yaml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README.md
        uses: ./

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update README.md tables on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated README.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to action.yaml file"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: true
          labels: bot,docs
